name: 🚀 Deploy website on push
on:
  push:
    branches: 
      - master
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.opediatech.com
        username: opediaftp@opediatech.com
        password: OTxFrzoil(Ao